# Generated by Django 3.2 on 2021-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='rating',
            new_name='counter_rating',
        ),
        migrations.AddField(
            model_name='courses',
            name='sum_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
